# Generated by Django 2.0.4 on 2018-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180407_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
